# Generated by Django 4.2.4 on 2023-12-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bedrooms", models.IntegerField()),
                ("location", models.CharField(max_length=100)),
                ("square_footage", models.FloatField()),
                ("price", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
